### ISSUE TITLE
Link to HTML version of SOP gives error

### ISSUE THREAD

**Issue by evomellor** [acoppock/Green-Lab-SOP#6]
Hello! I refer to this site frequently, thanks for making it! 

Issue is: I get an error when trying to go to the HTML version of the SOP: http://htmlpreview.github.io/?https://github.com/acoppock/Green-Lab-SOP/blob/master/Green_Lab_SOP.html

**Comment by acoppock** [comment]
Many thanks for the pointer!  I've updated the readme.  The html version can now be found here:
http://acoppock.github.io/Green-Lab-SOP/Green_Lab_SOP.html
